### ISSUE TITLE
Allow for import as well as export. 

### ISSUE THREAD

**Issue by triptych** [jackschaedler/goya#26]
Would be nice to be able to save state and send that off to someone via email, or to be able to work on an image across sessions, etc.

**Comment by jackschaedler** [comment]
Yes, this is unfortunately the major fault in the app right now. I unfortunately don't know enough about front-end dev to know if it's possible to allow loading files entirely on the client-side.

One option is to allow users to export a proprietary file format (.goy) which can be reloaded to allow for further work. Another option is to allow copy/paste of png (or other image) data, but this is unsatisfactory because I'm working towards adding animation support and you really want the user to be able to export an entire session (multiple frames).

I know that working with something like node-webkit would allow local file access, but I'd ideally like to keep the app as simple as possible. If you have expertise in this area, let me know!

One idea I've toyed around with is allowing the user to export the app state as a gist, which could be reloaded or shared.

**Comment by jackschaedler** [comment]
So presumably, the app state could be serialized and exported as a plain text file, and then loaded back in via menu command:
http://stackoverflow.com/questions/4950567/reading-client-side-text-file-using-javascript

Again, if you have expertise in this area, any help would be appreciated. Otherwise, i'll give it a crack this weekend.

**Comment by jackschaedler** [comment]
Added as part of 6cf6bd0a35776ea281a62eaa23265f99c740ee3e
